[package]
name = "rust-rss-indexer"
version = "0.1.0"
authors = ["avigael <code@gaels.us>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.10.4", features = ["blocking"] }
rss     = "1.9.0"
scraper = "0.11.0"
url     = "2.1.1"
